Python linter
curiefense/curiefense pull request #163
Opened 2021-02-23 20:57 UTC by xavier-rbz

This pull request adds automated python linting tests, showing warnings and errors. It will help solving the Python part of #146

2021-02-24 07:30 UTC, flaper87 requested changes

2021-02-24 07:30 UTC, flaper87 commented on .github/workflows/run-pylint.yml
> +        run: pip install pylint
Not to start a long discussion on linters, tools, and whatnot. Do you think we could use `black` here instead of `pylint`?

https://black.readthedocs.io/en/stable/

2021-02-24 17:04 UTC, xavier-rbz commented on .github/workflows/run-pylint.yml
> +        run: pip install pylint
If I understand black correctly, it's a code formatter only, it doesn't issue warnings or errors like pylint does. The "code analysis" part of pylint is what I wanted to add with this PR.
Yes, we could decide use black to format code (my personal answer would be "why not" rather than an enthusiastic "yes").

2021-02-25 21:25 UTC, jdorfman commented on .github/workflows/run-pylint.yml
> +        run: pip install pylint
@flaper87 thoughts? ^

2021-02-26 16:59 UTC, flaper87 commented on .github/workflows/run-pylint.yml
> +        run: pip install pylint
@xavier-rbz Correct! I guess where I'm coming from is that adopting `black` to format the code should remove the need of doing a lint check. We could just check if the code is "black'ed out".

This removes the need of installing the client, server, e2e, etc. We would have to have black (there's a container somewhere for it already) and pass it the paths we want to check.

makes sense?

2021-02-26 17:04 UTC, flaper87 approved these changes
:spaghetti:

2021-02-26 17:04 UTC, flaper87 commented on .github/workflows/run-pylint.yml
> +        run: pip install pylint
I don't think we have to block this PR on this, tho. Let's move it forward and switch to black later on

2021-02-27 08:41 UTC, flaper87 commented
sending through, I will work on moving things to use `black` instead

2021-02-27 08:41 UTC, merged