control flow with peripherial matching and custom actions
curiefense/curiefense pull request #194
Opened 2021-03-01 11:51 UTC by tzuryby

custom ersponse tested 
ttl expiration
HCA matching

2021-03-01 17:49 UTC, flaper87 reviewed
none of my comments are blockers, although there are some CI failures that would be nice to fix before getting this in.

2021-03-01 17:49 UTC, flaper87 commented on curiefense/curielogger/convert-bq/convert.py
> +
This is missing the `geo` data that I added in the server. I can work on a PR myself to add it to the repo.

2021-03-01 17:49 UTC, flaper87 commented on curiefense/curielogger/convert-bq/steps.md
> +done
Is there a chance for us to use curielogger directly here instead of doing the convert and then bulk insert? It looks like this is a great opportunity for dogfooding but I may be missing something.

2021-03-01 18:11 UTC, xavier-rbz requested changes
I'd like to postpone merging until we have passing e2e tests for this feature

2021-06-14 06:02 UTC, flaper87 commented
@tzuryby is this PR still relevant? Or will it be superseded by the Rust rewrite?

2021-07-13 03:15 UTC, closed without merging