[curielogger] Add docker-compose e2e tests
curiefense/curiefense pull request #209
Opened 2021-03-03 06:23 UTC by flaper87

2021-03-03 17:56 UTC, xavier-rbz commented on deploy/deploy-ci-compose.sh
> +dcoker-compose up -d --env-file "$WORKDIR/ci-env"
```suggestion
docker-compose up -d --env-file "$WORKDIR/ci-env"
```

2021-03-03 18:04 UTC, xavier-rbz requested changes

2021-03-03 18:04 UTC, xavier-rbz commented on deploy/deploy-ci-compose.sh
> +mkdir -p "$WORKDIR/bucket"
with docker-compose, `/bucket` doesn't need to be mounted on the host, the default should be fine. Unless you plan to do something with these files, this can be removed.

2021-03-03 18:04 UTC, xavier-rbz commented on deploy/deploy-ci-compose.sh
> +CURIE_BUCKET_LINK=file://$WORKDIR/bucket/prod/manifest.json
Does this work? It means that containers will try to read to that location, which is not mounted; by default, the bucket is located at `/bucket` inside the containers

2021-03-03 18:04 UTC, xavier-rbz commented on deploy/deploy-ci-compose.sh
> +docker-compose logs
maybe filter logs using `e2e/logs-smoke-test/checklogs-compose.sh`? That script removes logs we know about, that are expected. I typically use it this way:
```
cd e2e/logs-smoke-test/
./checklogs-compose.sh
grep . *log
```

2021-03-05 10:33 UTC, flaper87 commented
@xavier-rbz and I worked on this one so, sending it through now.

2021-03-05 10:34 UTC, merged