Run CI jobs only on PRs to target
curiefense/curiefense pull request #242
Opened 2021-03-15 06:31 UTC by flaper87

Signed-off-by: Flavio Percoco <flavio@reblaze.com>

2021-03-15 08:10 UTC, Aviv-Galmidi requested changes

2021-03-15 08:10 UTC, Aviv-Galmidi commented on .github/workflows/run-curieconf-tests.yml
> +    paths:
These are the paths for the UI tests and not the Python tests. The correct paths are:
- "curiefense/curieconf/**" instead of "curiefense/ui/**"
- ".github/workflows/run-curieconf-tests.yml" instead of ".github/workflows/run-curieconf-client-tests.yml"

2021-03-18 18:10 UTC, flaper87 commented on .github/workflows/run-curieconf-tests.yml
> +    paths:
jeez, too much copy pasta :D

2021-03-21 08:06 UTC, Aviv-Galmidi approved these changes

2021-03-21 15:20 UTC, merged