curielogger: cleanup duplicated fields
curiefense/curiefense pull request #307
Opened 2021-04-05 07:17 UTC by flaper87

Signed-off-by: Flavio Percoco <flavio@reblaze.com>

2021-04-05 08:05 UTC, flaper87 commented on e2e/test_e2e.py
> -        else:
@xavier-rbz Do you know/remember why this was needed? I would rather just use ES' DSL if this SQL query is not required :)

2021-04-05 08:38 UTC, Aviv-Galmidi commented on e2e/test_e2e.py
> -        else:
The path "/logs/api/v1/exec/" was the old API path we used for requesting logs before we switched over to ELK and it is no longer in use, if that helps you in any way :)

2021-04-08 06:50 UTC, xavier-rbz requested changes

2021-04-08 06:50 UTC, xavier-rbz commented on curiefense/curielogger/curielogger/main.go
> -					OriginalPath: req.GetOriginalPath(),
shouldn't `OriginalPath` be removed from common.go?

2021-04-08 06:50 UTC, xavier-rbz commented on curiefense/curielogger/curielogger/common.go
May I suggest updating `es_index_template.json` to reflect these changes?

2021-04-08 06:57 UTC, flaper87 commented on curiefense/curielogger/curielogger/common.go
> May I suggest updating es_index_template.json to reflect these changes?

Oh, man! I can't believe I forgot to do this :facepalm:

2021-04-11 18:23 UTC, xavier-rbz approved these changes

2021-04-12 05:09 UTC, merged