[ui] make url to swagger configurable
curiefense/curiefense pull request #338
Opened 2021-04-26 16:43 UTC by xavier-rbz

Signed-off-by: Xavier <xavier@reblaze.com>

2021-04-27 07:22 UTC, Aviv-Galmidi requested changes
We also need to bump the UI version for any change using `npm version patch` inside the ui folder

2021-04-27 07:22 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/__tests__/SideMenu.spec.ts
> +        swagger_url: swaggerURL,
There are two tests for Analytics menu items called `should render all Analytics menu items when db key exists` and `should render all Analytics menu items when db key does not exist`

We should alter the Settings menu items test called `should render all Configuration menu items` to match these two tests and check that the swaggerURL is presented correctly from the DB or from defaults

2021-04-28 19:54 UTC, xavier-rbz commented on curiefense/ui/src/components/SideMenu.vue
>        this.menuItems.analytics.kibana = {
done

2021-04-28 19:54 UTC, xavier-rbz commented on curiefense/ui/src/components/__tests__/SideMenu.spec.ts
> +        swagger_url: swaggerURL,
done

2021-04-28 19:56 UTC, xavier-rbz commented
Thanks for the review @Aviv-Galmidi! I have fixed the mistakes you have identified.

2021-05-03 09:23 UTC, Aviv-Galmidi approved these changes

2021-05-03 09:24 UTC, merged