jd-readme-updates
curiefense/curiefense pull request #344
Opened 2021-05-04 00:33 UTC by jdorfman

Signed-off-by: Justin Dorfman <justindorfman@gmail.com>

2021-05-04 00:35 UTC, jdorfman commented
This came from a conversation @tzuryby and I were having in Slack:

```
Tzury Bar Yochay Mar 22nd at 3:23 AM
Nice thread about the importance of README.md  and how to get it done right
https://news.ycombinator.com/item?id=26537805
```

```
Justin Dorfman  1 month ago
Yes ours can definitely use some love, it is on my todo list
```

2021-05-07 06:42 UTC, xavier-rbz commented on README.md
> +helm install curiefense
that doesn't work currently, right?

2021-05-07 13:13 UTC, jdorfman commented on README.md
> +helm install curiefense
It's in the docs ¯\_(ツ)_/¯

2021-05-07 14:16 UTC, jdorfman commented on README.md
> +helm install curiefense
Removed

2021-05-10 16:15 UTC, flaper87 requested changes

2021-05-10 16:15 UTC, flaper87 commented on README.md
> +## 📚 Documentation
Can we have the Docs at the top? I love it when the README shows docs right there without me having to scroll anywhere

2021-05-10 17:48 UTC, jdorfman commented on README.md
> +## 📚 Documentation
For sure

2021-05-11 04:57 UTC, merged