Flow Control - Editing count by entries always edit the first entry as well
curiefense/curiefense pull request #383
Opened 2021-06-21 12:11 UTC by denis-reblaze

2021-06-21 13:08 UTC, Aviv-Galmidi requested changes

2021-06-21 13:08 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/__tests__/LimitOption.spec.ts
> +  const WANTED_INDEX: Number = Math.floor ( Math.random() * 10000 )
Please keep naming to the typescript convention - lowerCamelCase

2021-06-21 13:15 UTC, denis-reblaze commented on curiefense/ui/src/components/__tests__/LimitOption.spec.ts
> +  const WANTED_INDEX: Number = Math.floor ( Math.random() * 10000 )
typescript convention for the constants is CONSTANT_CASE https://google.github.io/styleguide/tsguide.html

2021-06-21 14:16 UTC, Aviv-Galmidi commented
Let's add a test case which tests this bug - when there are multiple count by keys in flow control and we change one of them, assert that it changed and no other count by keys have changed

2021-06-22 14:21 UTC, Aviv-Galmidi requested changes

2021-06-22 14:21 UTC, Aviv-Galmidi commented on curiefense/ui/src/doc-editors/__tests__/FlowControlEditor.spec.ts
> +  const docs: FlowControl[] = [
This pattern is intentional as we might mutate the 'docs' variable within the tests. As we don't want tests to leak and influence one another, we're resetting docs to an initial state before each test run

2021-06-22 16:01 UTC, Aviv-Galmidi approved these changes

2021-06-29 11:08 UTC, Aviv-Galmidi submitted a review, later dismissed

2021-07-05 04:01 UTC, flaper87 commented
@denis-reblaze This needs rebase, any chance you can take care of it?

2021-07-07 11:39 UTC, denis-reblaze commented
I 'll create another pr for this feature since this pr is incorrect (accidentally made on main branch)

2021-07-07 11:39 UTC, closed without merging