Rust curieproxy
curiefense/curiefense pull request #385
Opened 2021-06-22 07:56 UTC by bartavelle

So this is the Rust PR. Unfortunately, it comes with other changes (mostly flowcontrol & tag actions in the lua code).

Tag actions are not yet implemented in Rust. Also missing is e2e testing with nginx, but It requires syslog support first.

2021-06-22 08:39 UTC, tzuryby approved these changes
all good. 
from now on. rust is the default engine.

2021-06-22 13:00 UTC, flaper87 requested changes
@bartavelle Can you check the various failures? I'd like to make sure CI passes before we send this through.

2021-06-22 13:24 UTC, bartavelle commented
Are the lua tests supposed to pass? I will fix the others right now.

2021-06-23 09:16 UTC, xavier-rbz requested changes

2021-06-23 09:16 UTC, xavier-rbz commented on curiefense/images/curieproxy-envoy/Dockerfile
> +ARG RUSTBIN_TAG=latest
using a "latest" tag might lead to embedding a binary that is not well characterized. I'd rather have the binary built in this Dockerfile, or having a specific version instead of "latest"

2021-06-23 09:32 UTC, xavier-rbz commented
I'd rather have latency test results before merging this.

2021-06-23 09:43 UTC, xavier-rbz requested changes

2021-06-23 09:43 UTC, xavier-rbz commented on curiefense/curieproxy/rust/curiefense-lua/src/iptools/avltree.rs
> +                panic!("Internal error: AVLTree balance factor={}. Should be in [-2;2]", bf);
let's never panic.

2021-06-23 09:43 UTC, xavier-rbz commented on curiefense/curieproxy/rust/curiefense/src/config/profiling.rs
> +            None => panic!("invariant violated, elems is empty!"),
let's never panic. panic leads to a crash of envoy, which should never happen.

2021-06-23 09:46 UTC, xavier-rbz submitted a review, later dismissed
I see that this implement control flows. We need to have:
* specifications for this feature
* documentation for this feature
* e2e tests for this feature

2021-06-25 15:23 UTC, alexcohn-rbz commented on curiefense/curieproxy/lua/nativeutils.lua
> +  return string.find(self, arg, #self - #arg + 1, true) == #self - #arg + 1
I believe that `string.sub(self, 1, #arg) == arg` is much faster especially if `arg` is short.

2021-06-28 08:42 UTC, bartavelle commented
> I see that this implement control flows. We need to have:
> 
>     * specifications for this feature
> 
>     * documentation for this feature
> 
>     * e2e tests for this feature

I wrote some specification/documentation in the usual document. I will add e2e tests now.

2021-06-28 16:12 UTC, bartavelle commented
> @bartavelle Can you check the various failures? I'd like to make sure CI passes before we send this through.

All tests are green!

2021-06-29 04:10 UTC, flaper87 commented
@bartavelle is the plan to address the following comments from @xavier-rbz in this PR?

* https://github.com/curiefense/curiefense/pull/385#pullrequestreview-690438627
* https://github.com/curiefense/curiefense/pull/385#issuecomment-866684604

2021-06-29 08:51 UTC, bartavelle commented on curiefense/images/curieproxy-envoy/Dockerfile
> +ARG RUSTBIN_TAG=latest
This is actually the default value, and it is overridden in `build-docker-images.sh`, so I believe we're good.

2021-06-29 13:27 UTC, bartavelle commented
@xavier-rbz @flaper87 I think the PR is in a much better shape now. Does it address your comments?

The main problem is that the new features do not have e2e tests, but they all have "lua tests" that run during the rust build phase.

2021-06-29 13:39 UTC, flaper87 commented
> The main problem is that the new features do not have e2e tests, but they all have "lua tests" that run during the rust build phase.

This is a more promising situation. I think we can start getting this in and work on the remaining tasks on follow-up PRs.

Can you work on an e2e tests for the new feature as the next task?

I will squash this into a single commit. It's a quite big PR, which is unfortunate :)

2021-06-29 13:39 UTC, flaper87 approved these changes

2021-06-29 13:40 UTC, merged