RR-695 Tag rules validation
curiefense/curiefense pull request #416
Opened 2021-07-06 12:48 UTC by denis-reblaze

Validation of tag rule entries (disallow duplicated entries and disallow incorrect symbols depending on the entry category)

2021-07-08 11:44 UTC, Aviv-Galmidi requested changes

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +        const sectionsMsg = (number: number) => this.rule.sections.length > 1 ? `Section ${number+1}: ` : '';
There's no need for this function, as you call it in one location you can simply add it instead of creating a function

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    resetDuplicates() {
There's no need for this function, as you call it in one location you can simply add it instead of creating a function

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    isEntryDuplicate( sIdx: number, [curCat, curVal]: [string, TagRuleSectionEntry[1]] ) {
please give more meaningful names over `sIdx`, `curCat`, `carVal`

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    isEntryDuplicate( sIdx: number, [curCat, curVal]: [string, TagRuleSectionEntry[1]] ) {
the type of the 2nd arg should be `TagRuleSectionEntry`

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +          ( prev: string, [section, category, value]: [ number, Category, string] ) => `
the type of the 2nd arg should be TagRuleSectionEntry

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    validateValue( sectionId: number, target: HTMLInputElement ) {
Please try to keep the same name if we're using the same attribute. `sectionId` should be `sectionIndex` as it is what you've used in other functions

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      target.style.height = `${target.scrollHeight}px`;
Please add a class instead of inline style

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const ipPattern = /((^\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\s*(:([0-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]
Are you certain about this IP regex? in URL Maps we use a much simpler pattern recognizer as described below
`/^((((\d{1,3})\.){3}\d{1,3}(\/\d{1,2}))|([0-9a-f]+:+){1,8}([0-9a-f]+)?(\/\d{1,3})?)$/`

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const ipList = target.value.split('\n').filter( (ip) => ip );
why do you need `.filter( (ip) => ip )` it looks like it will just return all results, did you intend to filter out empty lines?

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      this.errorsIps = [];
invalidIPs is more accurate grammatically

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    validateNotEmpty( id: string, target: HTMLInputElement ) {
What if instead of sending the target to all these functions we would send the string we'd like to evaluate? We can also make these functions more generic this way and even move them to Utils.ts to be used in other parts of the system later on

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    onSecondAttr( sectionIndex: number, target: HTMLInputElement ) {
onSecondAttr what? change? input?

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const {isCategoryArgsCookiesHeaders, newEntryCategory, isError} = this;
I don't think we need destructuring assignment for something this simple, we're adding new variables which are not needed
You can simply call `this.isCategoryArgsCookiesHeaders(this.newEntryCategory) && this.isError(`${this.newEntryCategory}${sectionIndex}-secondAttr`)`

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const {isCategoryArgsCookiesHeaders, newEntryCategory, validateRegex} = this;
I don't think we need destructuring assignment for something this simple, we're adding new variables which are not needed

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const {validateNotEmpty, newEntryCategory, validateIp, validateRegex} = this;
I don't think we need destructuring assignment for something this simple, we're adding new variables which are not needed

2021-07-08 11:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const val = target.value.trim();
General note, our linter should fail for semicolons at end of lines. It's currently set to 'off' instead of 'never'. If you want to discuss this we can decide to add them, but for now let's remove all semicolons to keep the code unified

2021-07-08 15:34 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    resetDuplicates() {
Since function name is supposed to reflect what it does, having a function is more readable than a line of code especially if there're no comments

2021-07-08 15:48 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const {isCategoryArgsCookiesHeaders, newEntryCategory, isError} = this;
I don't know what's the reason to save on local variables if it helps to increase the readability. While in your example one can broke his eyes, mine looks much better:
`isCategoryArgsCookiesHeaders(newEntryCategory) && isError(${newEntryCategory}${sectionIndex}-secondAttr)`

2021-07-08 15:48 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const {isCategoryArgsCookiesHeaders, newEntryCategory, validateRegex} = this;
I don't know what's the reason to save on local variables if it helps to increase the readability.

2021-07-08 15:49 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const {validateNotEmpty, newEntryCategory, validateIp, validateRegex} = this;
I don't know what's the reason to save on local variables if it helps to increase the readability.

2021-07-08 16:01 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const ipPattern = /((^\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\s*(:([0-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]
I'm certain this regex works while that one from url maps doesn't (I checked on "1.1.1.1")

2021-07-08 16:03 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +      const ipList = target.value.split('\n').filter( (ip) => ip );
Of course

2021-07-08 16:19 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +    addError( field: string ) {
Quite opposite, the current implementation is the simplest to understand and maintain: you provide any unique string without the need to get some category and sectionIndex. This way you can use the function as in the validateDuplicates function:
`this.addError( 'duplicate' )`
`this.clearError( 'duplicate' )`

2021-07-08 16:29 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +          ( prev: string, [section, category, value]: [ number, Category, string] ) => `
Nope, the type comes from `this.duplicatedEntries` which is filling in `validateDuplicates` function:
`this.duplicatedEntries.push( [sectionIndex, category, value] )`
where category is the first element of entry, while entry is an array like [category, [newEntryName, newEntryValue]]

2021-07-11 08:53 UTC, Aviv-Galmidi requested changes

2021-07-11 08:53 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/DocumentEditor.vue
> +            @form-valid="isDocumentInvalid = $event"
You're assigning `form-valid` value into `isDocumentInvalid` (valid -> invalid)
Also there are other locations which use this event, so make sure you're updating them as well if you change the implementation

2021-07-11 08:53 UTC, Aviv-Galmidi commented on curiefense/ui/src/doc-editors/__tests__/ProfilingListEditor.spec.ts
> +      expect(wrapper.emitted('form-valid')).toBeTruthy()
form-valid would be false if you emit valid false

2021-07-11 08:53 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/EntriesRelationList.vue
> +        this.$emit('valid', !!value.length)
You emit valid if there is length = if there are errors

2021-07-11 11:36 UTC, denis-reblaze commented on curiefense/ui/src/views/DocumentEditor.vue
> +            @form-valid="isDocumentInvalid = $event"
done

2021-07-11 11:37 UTC, denis-reblaze commented on curiefense/ui/src/doc-editors/__tests__/ProfilingListEditor.spec.ts
> +      expect(wrapper.emitted('form-valid')).toBeTruthy()
done

2021-07-11 11:44 UTC, denis-reblaze commented on curiefense/ui/src/components/EntriesRelationList.vue
> +        this.$emit('valid', !!value.length)
done

2021-07-11 11:51 UTC, Aviv-Galmidi submitted a review, later dismissed

2021-07-11 12:33 UTC, Aviv-Galmidi approved these changes

2021-07-11 13:34 UTC, merged