utils.rs - method, authority and path
curiefense/curiefense pull request #417
Opened 2021-07-06 14:34 UTC by tzuryby

utils.rs - method, authority and path

2021-07-07 05:59 UTC, flaper87 requested changes
@tzuryby do you think you can split this PR in 2? One for the changes in `utils.rs` and the other one for `waf.rs`. These look like unrelated changes so I would like to tackle the changes separately.

The change to `utils.rs` will solve #410 as far as I can tell.

2021-07-07 05:59 UTC, flaper87 commented on curiefense/curieproxy/rust/curiefense/src/utils.rs
> +                // "extra": self.rinfo.meta.extra
can we remove this line here? Doesn't look it's needed/used

2021-07-12 05:24 UTC, flaper87 requested changes

2021-07-12 05:24 UTC, flaper87 commented on curiefense/curieproxy/rust/curiefense/src/waf.rs
> +                // }
It'd be nice to remove all the commented lines before merging this PR :)

2021-07-12 05:24 UTC, flaper87 commented on curiefense/curieproxy/rust/Dockerfile
> +RUN luarocks install lua-cjson
Is this just a test?

2021-07-12 07:45 UTC, bartavelle commented
Of course I did not realize there already was a pull request for this! I just proposed #442 .

2021-07-12 07:48 UTC, flaper87 commented
> Of course I did not realize there already was a pull request for this! I just proposed #442 .

It's ok! This one is doing a bit more than it should 😂

2021-07-13 03:13 UTC, tzuryby commented
@bartavelle merged those in his code already.

2021-07-13 03:13 UTC, closed without merging