UI error handling
curiefense/curiefense pull request #423
Opened 2021-07-08 14:58 UTC by denis-reblaze

2021-07-08 15:32 UTC, Aviv-Galmidi requested changes

2021-07-08 15:32 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/RequestsUtils.ts
> +const sendRequest = (requestParams: IRequestParams) => {
What is the reason behind changing this function to receive an object instead of params?

2021-07-08 15:32 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/DBEditor.vue
> +      selectedDatabaseData: {} as {[key: string]: string},
The value type is not a string but a json, you can use the type GenericObject to represent this

2021-07-08 15:32 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/DBEditor.vue
> +      this.selectedDatabaseData = response ? response.data || {} : {}
We can use elvis opreator (optional chaining) here  `this.selectedDatabaseData = response?.data || {}`

2021-07-08 15:32 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/DBEditor.vue
> +                          :disabled="!selectedDatabase"
Perhaps this should check for both selectedDatabase and selectedKey

2021-07-08 15:32 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/DocumentEditor.vue
> +          `Switched to document ${docName ? `"${docName}" ` : ''}with ID "${this.selectedDocID}".`,
It would be better to not toast if the document name is empty, or toast with something like 'Switched to unknown document'

2021-07-08 15:32 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/VersionControl.vue
> +                     :loading="loadingGitlog"
There are other locations which use gitHistory component which will need this change as well

2021-07-08 18:37 UTC, denis-reblaze commented on curiefense/ui/src/assets/RequestsUtils.ts
> +const sendRequest = (requestParams: IRequestParams) => {
I had to add an argument onFail which is a callback executing when axios request fails. But the function already has 7 arguments, some of which are optional, so through the code we have such examples as
`RequestsUtils.sendRequest('GET', url, null, null, something, null, somethingElse)`

So the option to simply add an argument would be the worst decision as it would require from developer to write smth like
`RequestsUtils.sendRequest('GET', url, null, null, null, null, null, onFail)`

Anyway, regardless the current PR, this function definitely must be refactored.

2021-07-08 18:53 UTC, denis-reblaze commented on curiefense/ui/src/views/DBEditor.vue
> +                          :disabled="!selectedDatabase"
If selectedDatabase is falsy then selectedKey is definitely falsy, no reason to check it

2021-07-11 08:58 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/RequestsUtils.ts
> +const sendRequest = (requestParams: IRequestParams) => {
What refactor would you like to see in the funciton? Let's dicuss this

2021-07-11 11:16 UTC, denis-reblaze commented on curiefense/ui/src/assets/RequestsUtils.ts
> +const sendRequest = (requestParams: IRequestParams) => {
the same as described above.
in addition, but not that necessarily, some lines could be simplified

2021-07-11 11:50 UTC, Aviv-Galmidi approved these changes

2021-07-11 13:13 UTC, merged