Tags underscore
curiefense/curiefense pull request #473
Opened 2021-07-14 07:22 UTC by denis-reblaze

Disallow non alphanum and ':' symbols in tags
tags are all lowercase too

2021-07-14 09:28 UTC, Aviv-Galmidi requested changes

2021-07-14 09:28 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/Utils.ts
> +const filterTag = (tag: string) => tag.replace(/[^\w: ]|_/g, '-')
As this is something which we will only use in relations to tags I think we should move this to TagsAutoComplete component, I don't think we'll be using this function anywhere else

2021-07-14 09:28 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/AutocompleteInput.vue
> +      autocompleteValue: filterFunction ? filterFunction( initialValue ) : initialValue,
Please make sure we also add this filter function on the watch of `initialValue`

2021-07-14 13:44 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/AutocompleteInput.vue
> +      if ( this.autocompleteValue !== newVal ) {
Should be `this.autocompleteValue !== newValFiltered` as it might be the same as new value but not the filtered new value
For instance if the filter is `(val) => val * 2` and we pass 2 as the initial value and then update it to 4, autocompleteValue would be 4 which would cause it to not update

2021-07-15 07:51 UTC, denis-reblaze commented on curiefense/ui/src/components/AutocompleteInput.vue
> +      if ( this.autocompleteValue !== newVal ) {
No, this will make the value filtered immediately on keypress while we want filter it on submit (on pressing space or etc.)

2021-07-19 11:00 UTC, Aviv-Galmidi commented
Adding github hooks: This PR closes https://github.com/curiefense/curiefense/issues/455

2021-07-19 11:53 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/AutocompleteInput.vue
> +      if ( this.autocompleteValue !== newVal ) {
But right now it can cause an issue as I described above
> if the filter is (val) => val * 2 and we pass 2 as the initial value and then update it to 4, autocompleteValue would be 4 which would cause it to not update
We'll need to think of a way to update the value on submit but also on initialValue changes

2021-07-22 07:05 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/AutocompleteInput.vue
> +      if ( this.autocompleteValue !== newVal ) {
Can't think of a real-world scenario where this would apply in, as replacing strings would always be different than the newVal if newVal is invalid and thus end up with the value being filtered. resolving the convo

2021-07-22 07:06 UTC, Aviv-Galmidi approved these changes

2021-07-25 11:55 UTC, merged