Fixed bug where empty tags were being added to entities
curiefense/curiefense pull request #510
Opened 2021-07-21 11:35 UTC by Aviv-Galmidi

Closes https://github.com/curiefense/curiefense/issues/495
Changed autocomplete error message to not include the word 'tag' as they should be generic and not implementation-specific

Signed-off-by: Aviv.Galmidi <AvivGalmidi@gmail.com>

2021-07-21 12:49 UTC, denis-reblaze commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.buildTagsSuggestionsFromData(response?.data || {})
I suggest to refactor the RequestsUtils.sendRequest function so as to always have a response defined (by adding `return {}` at the end of the catch block, or even `return {data: {}}`, or even `return {status: 500, data: {}}`)

2021-07-21 12:49 UTC, denis-reblaze commented on curiefense/ui/src/components/AutocompleteInput.vue
> +            `Values must be at least ${this.minimumValueLength} characters long.`,
But you told toasts is not the mechanism to display errors, why do we have it here?

2021-07-21 12:49 UTC, denis-reblaze commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.tag = newTag.replace(/\s\s+/g, ' ')
Duplicates line 174, should be implemented as a separate function

2021-07-22 07:30 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.buildTagsSuggestionsFromData(response?.data || {})
I do not agree that sendRequest should always return an object with data, when the server returns status 500. Perhaps we should return response.data directly from RequestUtils but that's
Anyhow, that's another discussion all together, this line is a hotfix as the tests were not being run for this component after the latest changes for RequestUtils

2021-07-22 07:35 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/AutocompleteInput.vue
> +            `Values must be at least ${this.minimumValueLength} characters long.`,
A couple of things
1) I said toasts are not a mechanism to display *temporary* errors, this is an attempt to submit a tag(or value) which results in a permanent error - we do not apply the new tag and remove it from the input. Unlike field validation, you can't change the value again as it is being deleted. This error is closer to the "failed to save" error than field validation errors
2) I still agree that it is not the optimal way of displaying the error, the error should be directly next to the error-prone field. However, this all area of code is going to be modified soon as we move the tag creation process to the new system. This change was because AutoCompleteInput shouldn't know what "tags" are as they're a single implantation of the auto complete and thus this message should be more generic to all usecases

2021-07-22 07:53 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.tag = newTag.replace(/\s\s+/g, ' ')
Fixed, moved to a new function in Utils.ts

2021-07-22 12:05 UTC, denis-reblaze requested changes

2021-07-22 12:05 UTC, denis-reblaze commented on curiefense/ui/src/assets/Utils.ts
> +  return value.replace(/\s\s+/g, ' ')
The function will throw an exception if the value is, for example, undefined

2021-07-22 12:37 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.buildTagsSuggestionsFromData(response?.data || {})
I did not say it is better than a single `return {}` but you did not suggest a signle `return {}` you suggested to `return {data: {}}`
If you re-read my comment you'll see I had a problem with the `data: {}` part as responses with server status 500 shouldn't have data attribute in them

2021-07-22 12:42 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/AutocompleteInput.vue
> +            `Values must be at least ${this.minimumValueLength} characters long.`,
Of course they are technical terms, and they have technical meanings as well
We display some error in toast messages as they are always true - the server request failed, sending it again does not change the fact that the inital request failed. Attempting to submit a tag with 2 characters fails, further attempts do submit a different tags with more characters do not change this fact.
We do not display temporary errors in toasts - the input is currently not a valid email, you can change it and it will be a valid email, it is still the same input data, so once you change it you'd need to cancel out the error which cannot be done with toasts (technically can be done, but that's not how toasts perform, they're a messaging system)

2021-07-22 12:48 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/Utils.ts
> +  return value.replace(/\s\s+/g, ' ')
There is little to no benefit to writing it in a single line
Multiple lines are more readable and are easier to maintain, you're saving a few bytes of data but that's negligible

2021-07-22 12:48 UTC, denis-reblaze commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.buildTagsSuggestionsFromData(response?.data || {})
Seems that rather you need to re-read my comment: `return {}` was the very first suggestion.

2021-07-22 12:55 UTC, denis-reblaze commented on curiefense/ui/src/assets/Utils.ts
> +  return value.replace(/\s\s+/g, ' ')
The benefit is not in bytes but in saving a developer's eyes, and therefore increasing the development quality. Unnecessary `return`s here and there are clogging the code (btw, this was one of the goals of inventing arrow functions, why not to use it?)

2021-07-22 13:39 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/Utils.ts
> +  return value.replace(/\s\s+/g, ' ')
Fixed for all utils functions

2021-07-22 13:50 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.buildTagsSuggestionsFromData(response?.data || {})
I stand corrected, you sugged returning an empty object, but that's really not the point. All I've addressed is the fact that I do not think sendRequest should return data on errors, and we should hold a discussion to decide on the best implementation later on. I did not suggest adding `response?.data || {}` at every place where we implement sendRequest
I merely added a hotfix in order to fix the tests suite that was broken with the latest changes to sendRequests. I do not know the implications of changing the catch to return an object at the moment, and i do not have the capacity to run full manual tests for such a change before the release of 1.4.0

2021-07-22 14:47 UTC, denis-reblaze requested changes

2021-07-22 14:47 UTC, denis-reblaze commented on curiefense/ui/src/assets/Utils.ts
> +  message = message ? message : ''
It's better to use default function parameter or another variable

2021-07-22 14:47 UTC, denis-reblaze commented on curiefense/ui/src/components/AutocompleteInput.vue
> +            `Values must be at least ${this.minimumValueLength} characters long.`,
I got this idea from the previous comment, and the suggestion was to get rid of the technical meanings in order to look at the system as an ordinary user.

2021-07-22 14:47 UTC, denis-reblaze commented on curiefense/ui/src/assets/Utils.ts
> +  return value?.replace(/\s\s+/g, ' ') || ''
still potentially crushable if somehow the value's type won't be string

2021-07-22 14:47 UTC, denis-reblaze commented on curiefense/ui/src/components/TagAutocompleteInput.vue
> +      this.buildTagsSuggestionsFromData(response?.data || {})
ok, I hope this function will be refactored asap, when we have time

2021-07-22 14:56 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/Utils.ts
> +  message = message ? message : ''
Default function parameters do not overwrite null values, so that wouldn't work
Why do you believe a new vairable would help here?

2021-07-22 14:57 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/Utils.ts
> +  return value?.replace(/\s\s+/g, ' ') || ''
That's what typing is for in typescript, we don't need to check if value is a string as we require it to be typed as string

2021-07-22 15:17 UTC, denis-reblaze commented on curiefense/ui/src/assets/Utils.ts
> +  message = message ? message : ''
Correct, default parameter is not an option. About immutability it's written a lot, the main benefit is 

> simpler programming and debugging, as data that never changes is easier to reason about than data that is free to be changed arbitrarily throughout the app.

2021-07-22 15:23 UTC, denis-reblaze commented on curiefense/ui/src/assets/Utils.ts
> +  return value?.replace(/\s\s+/g, ' ') || ''
Ts helps on the dev step only. You're using the function in a component's event, which was emitted from another component - can you be sure that types are matched in this and the other cases? If yes, I'm calling this comment off, but in that case you need to remove the recently added checking `value? ||`.

2021-07-27 12:58 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/Utils.ts
> +  return value?.replace(/\s\s+/g, ' ') || ''
`value` is a string, it cannot be anything else other than `string`, `null`, or`undefined`. The `value?... || ''` check is in case the data sent to the function is either `undefined` or `null` in which case `.replace` would return an error

2021-07-27 12:58 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/AutocompleteInput.vue
> +            `Values must be at least ${this.minimumValueLength} characters long.`,
We are using toasts when they are applicable and we do not use toasts when they are not.

A toast can show an error if a user completed an action, but there was a system-related issue preventing the action from being fully executed
Of course we'll bind the technical meaning of an error to the usage of toasts and displaying of errors, because that's they are differrent types of errors. A system-related error in response to a user-submitted action is not the same type of error as a form field not complying with a pre defined set of rules

What you're suggesting is similar to this: `Let's remove button colors as positive buttons (blue) and negativie buttons (red) have the same meaning once we remove their technical meaning`. They have different technical meanings and thus different display patterns

2021-07-27 12:58 UTC, Aviv-Galmidi commented on curiefense/ui/src/assets/Utils.ts
> +  message = message ? message : ''
You're taking a qoute out of context, as this qoute is refering to react + redux change detection. If you want to bring a qoute you should bring the entire qoute.

> Immutability can bring increased performance to your app, and leads to simpler programming and debugging, as data that never changes is easier to reason about than data that is free to be changed arbitrarily throughout your app.
In particular, **immutability in the context of a Web app enables sophisticated change detection techniques to be implemented simply and cheaply** (emphasis mine), ensuring the computationally expensive process of updating the DOM occurs only when it absolutely has to (a cornerstone of React’s performance improvements over other libraries).

Javascript is using pass-by-value (in this case) which means this string will always be inclosed within this function and will only live inisde of it. The change will never have any ramifications on the change-detection process.

We do not have the risk of not understanding the change down the line, it is a simple default state in case `message` is `undefined` or `null` and it is like writing the following
```
if (!message) {
    message = ''
}
```

2021-07-30 06:58 UTC, flaper87 approved these changes

2021-08-03 11:17 UTC, merged