"Database" terminology changes
curiefense/curiefense pull request #530
Opened 2021-08-01 12:19 UTC by Freakachoo

Was decided to change some terminology for the "Database" page and related code.

- Databases -> CurieDB
- Databse -> Namespace
- Document -> Value

# Change log
### UI
- Databases (menu)
- On databases page
### Client-Side
- Refactored variables, function names and CSS classes names according to terminology changes above.
- `this.databases` stayed as is (from discussion with @Aviv-Galmidi )
### CurieProxy
Refactored variables, function names, comments and HTTP response texts according to terminology changes above.

2021-08-02 08:07 UTC, flaper87 reviewed
> Was decided to change some terminology for the "Database" page and related code.

We should always strive to have these conversations in the Curiefense slack and make sure they are linked here. At the very least, it would be good to have an issue summarizing any conversations, decisions, and rationale behind these changes.

Could you create one?

(cc @jdorfman FYI, as we need to work harder in encouraging folks to have more conversations in the community Slack)

2021-08-02 08:07 UTC, flaper87 commented on curiefense/curieconf/server/curieconf/confserver/v1/api.py
>  class DbResource(Resource):
Should this be renamed to `NSResource` ?

2021-08-02 09:22 UTC, Aviv-Galmidi submitted a review, later dismissed

2021-08-02 09:22 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/DBEditor.vue
>                        title="Document"
Should be changed as well
Document -> Value

2021-08-02 09:22 UTC, Aviv-Galmidi commented on curiefense/ui/src/views/DBEditor.vue
>        document: null,
Should be changed as well
document -> selectedKeyValue

2021-08-02 09:22 UTC, Aviv-Galmidi commented on curiefense/curieconf/server/curieconf/confserver/v1/api.py
> +        "Get the list of existing namespaces"
There are still some `DB`s in this file that should be changed

2021-08-02 10:35 UTC, flaper87 commented on curiefense/ui/src/components/SideMenu.vue
>            '/db': {
Wouldn't this be a backwards incompatible change? If we change any of the API's paths, we will have to bump the API version. (I get that this is vue only, just commenting here so we can keep this in mind for the entire PR

2021-08-02 10:38 UTC, Freakachoo commented on curiefense/curieconf/server/curieconf/confserver/v1/api.py
> +        "Get the list of existing namespaces"
DBs will be changed soon (i'm testing the changes now). You know, I thought that if paths didn't changed we don't need V2, but you're right - responses are also important, will rebuild it with v2, thank you!

2021-08-02 10:39 UTC, Freakachoo commented on curiefense/ui/src/components/SideMenu.vue
>            '/db': {
Are you sure? By meaning this is just database, CurieDB is just kind of marketing name. Don't you think? I would prefer to leave it as `db` - by initial meaning.

2021-08-02 11:09 UTC, Freakachoo commented on curiefense/ui/src/components/SideMenu.vue
>            '/db': {
@flaper87 I will add v2 anyway in CurieConf (see comment in another thread above), so the client-side will be changed to v2 too anyway.

2021-08-02 11:20 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/SideMenu.vue
>            '/db': {
The change I suggested would break the path of the CurieDB editor
However, I don't think the break is significant. The change would mean that if anyone bookmarked `https://example.com/db/` they would be redirected to the config page if they use this link
If it is siginificant and we do want to support backward compatibility in the client paths, then I'd suggest adding the new suggested path, as well as keeping `/db` path and redirecting it towards the new path

In general, I don't believe `/db` is  good path name, as it's not very descriptive nor informative

2021-08-02 11:22 UTC, Aviv-Galmidi commented on curiefense/ui/src/components/SideMenu.vue
>            '/db': {
The change I suggested would break the client path of the CurieDB editor
However, I don't think the break is significant. The change would mean that if anyone bookmarked `https://example.com/db/` they would be redirected to the config page if they use this link, but I can't think of any other time it would matter
If it is siginificant and we do want to support backward compatibility in the client paths, then I'd suggest adding the new suggested path, as well as keeping `/db` path and redirecting it to the new path

In general, I don't believe `/db` is good path name, as it's not very descriptive nor informative. This is something that has been bothering me for a while, but haven't gotten around to changing it yet

2021-08-02 11:48 UTC, Freakachoo commented on curiefense/ui/src/components/SideMenu.vue
>            '/db': {
Ok we've talked to @Aviv-Galmidi and clarified that the change is not about API path, but just a client-side path. So, it making sense to change it to `/CurieDB` if we have changed the menu name to CurieDB too.

2021-08-03 15:56 UTC, Freakachoo commented
@flaper87 @Aviv-Galmidi created API v2 and bumped client-side to use it. Please check. Yes, there are a lot of changes and a big PR, sorry, but what can we do, changes were needed.

2021-08-04 11:29 UTC, Freakachoo commented
@flaper87 @Aviv-Galmidi the API v2 was added, nginx configs were modified too, client-side was moved to use the v2. Please re-review.

2021-08-04 13:16 UTC, Freakachoo commented on curiefense/curieconf/server/setup.py
> +    version="1.1",
@flaper87 do we have a convention of progressing versions? API v2 is a big change, possibly we should make the version "2"

2021-08-09 13:15 UTC, shaisgv requested changes

2021-08-09 13:15 UTC, shaisgv commented on curiefense/curieconf/server/curieconf/confserver/backend/gitbackend.py
Why was the exception handling removed?

2021-08-09 13:15 UTC, shaisgv commented on curiefense/curieconf/server/curieconf/confserver/backend/gitbackend.py
> +            self.commit("Reverting namespace [%s] to version [%s]" % (nsname, version))
Exception removed again

2021-08-09 14:13 UTC, Freakachoo commented on curiefense/curieconf/server/curieconf/confserver/backend/gitbackend.py
Because the exception handling was moving to `/v1/api.py` and `/v2/api.py` so we may support different responses for different API versions.

2021-08-10 04:42 UTC, shaisgv approved these changes

2021-08-11 14:34 UTC, merged