Change term TagRule to GlobalFilter
curiefense/curiefense pull request #554
Opened 2021-08-12 09:45 UTC by Freakachoo

According to issue https://github.com/curiefense/curiefense/issues/552 the term `TagRule` was changed to `GlobalFilter`.

# Changelog
The term was changed for:
- UI
- URL Paths
- CurieConf and CurieProxy variables and functions names
- Filenames (json schema, config, initial_db)
- Kibana Dashboard (Blocked by TagRules -> Blocked by GlobalFilter)

Also, JSON schemas were divided into `v1` and `v2` and moved under corresponding folders.
Because the internal logic of a new term and API v2 was not changed (only name), function `vconvert` was created to convert between `v1` and `v2` terms.

# TODO
Update docs

2021-08-13 04:31 UTC, bartavelle approved these changes

2021-08-13 17:39 UTC, flaper87 requested changes
curietasker is failing to build:

```
2021-08-12T10:11:43.8576051Z Step 4/12 : COPY curieconf-server/curieconf/confserver/json/tag-rules.schema /tag-rules.schema
2021-08-12T10:11:43.8616803Z COPY failed: file not found in build context or excluded by .dockerignore: stat curieconf-server/curieconf/confserver/json/tag-rules.schema: file does not exist
```

Also, do you think we can update the `e2e` tests so that they won't fail :pray: 

Thanks for the work here :+1:

2021-08-23 06:43 UTC, flaper87 reviewed
This is fantastic, @Freakachoo 

I would ask @bartavelle to take a look, given the changes to the Rust part too.

2021-08-23 06:43 UTC, flaper87 commented on .github/workflows/e2e-minikube-filebeat.yml
> +            pytest --log-level INFO --base-protected-url http://$IPPORT --base-conf-url http://$IP:30000/api/v2/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:30200/ --junit-xml pytes
For a follow-up PR: Given that the compose tests pass, I wonder if we should try to enable all these for the istio+envoy based ones. It should be the same.

2021-08-23 07:05 UTC, flaper87 approved these changes
Please, use squash as the merge strategy

2021-08-23 07:51 UTC, bartavelle approved these changes

2021-08-23 07:56 UTC, Freakachoo commented on .github/workflows/e2e-minikube-filebeat.yml
> +            pytest --log-level INFO --base-protected-url http://$IPPORT --base-conf-url http://$IP:30000/api/v2/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:30200/ --junit-xml pytes
@yanushg ^^^ please consider adding this on a new tests implementation

2021-08-23 07:57 UTC, merged

2021-08-23 09:13 UTC, Mamba1981 commented on .github/workflows/e2e-minikube-filebeat.yml
> +            pytest --log-level INFO --base-protected-url http://$IPPORT --base-conf-url http://$IP:30000/api/v2/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:30200/ --junit-xml pytes
These tests will be enabled in new test implementation, thanks.