Full last name
curiefense/curiefense pull request #562
Opened 2021-08-17 11:32 UTC by wolfedale

I think full last name looks better :-)

2021-08-17 17:15 UTC, jdorfman commented on README.md
> +This project is named after the famous scientist [Marie Skłodowska-Curie](https://www.curiefense.io/marie-curie). It began in intensive work sessions at Malakoff France, close to her home and laborat
In this context, I think you are right. Wikipedia has it at "Marie Salomea Skłodowska Curie". Could you change it to that and I'll merge.

2021-08-18 08:32 UTC, wolfedale commented on README.md
> +This project is named after the famous scientist [Marie Skłodowska-Curie](https://www.curiefense.io/marie-curie). It began in intensive work sessions at Malakoff France, close to her home and laborat
Just changed it, thanks! :-)

2021-08-19 06:21 UTC, flaper87 commented
@wolfedale could you sign the commit so that the DCO check can pass? :) 

Here's some info: https://github.com/curiefense/curiefense/pull/562/checks?check_run_id=3359059053

2021-08-19 14:47 UTC, jdorfman commented
@wolfedale TL;DR

Run:

`git rebase HEAD~2 --signoff`

Now your commits will have your sign off. Next run

`git push --force-with-lease origin main`

2021-08-23 09:59 UTC, wolfedale commented
Does it looks fine now?

2021-08-24 02:38 UTC, jdorfman requested changes
@wolfedale need you to remove that hyphen =)

Should be: "Marie Salomea Skłodowska Curie"

not: "Marie Salomea Skłodowska-Curie"

2021-08-25 13:22 UTC, flaper87 approved these changes

2021-08-25 14:38 UTC, jdorfman approved these changes

2021-08-25 14:39 UTC, merged