Add a new request-level field "cfhost"
curiefense/curiefense pull request #620
Opened 2021-11-12 14:08 UTC by bartavelle

This field is the "host" that is used to select the security policy.

Close #619 

Signed-off-by: Simon Marechal <bartavelle@gmail.com>

2021-11-12 14:10 UTC, bartavelle commented
This modifies curielogger, review very much appreciated :)

2021-11-19 13:10 UTC, flaper87 commented on curiefense/curielogger/pkg/entities/curie_proxy_log.go
> +	Cfhost      string                 `json:"cfhost"`
Is this line really needed? Looking at the Rust changes it seems like we only need it in the `Request` struct.

2021-11-19 16:09 UTC, bartavelle commented on curiefense/curielogger/pkg/entities/curie_proxy_log.go
> +	Cfhost      string                 `json:"cfhost"`
TBH, I don't really know what I am doing ^^

2021-11-19 16:12 UTC, bartavelle commented on curiefense/curielogger/pkg/entities/curie_proxy_log.go
> +	Cfhost      string                 `json:"cfhost"`
Just remove that line.

2021-11-19 16:57 UTC, bartavelle commented on curiefense/curielogger/pkg/entities/curie_proxy_log.go
> +	Cfhost      string                 `json:"cfhost"`
Well, it didn't work :) I'll check taht monday

2021-11-23 09:16 UTC, bartavelle commented on curiefense/curielogger/pkg/entities/curie_proxy_log.go
> +	Cfhost      string                 `json:"cfhost"`
If I remove it, then this line won't work : https://github.com/curiefense/curiefense/pull/620/files#diff-eff0e05ed5e3dcc3b326158efb56f894ff52e568be3dff2017b85270036309f9R174

Am I doing something stupid here?

2021-12-16 07:51 UTC, flaper87 requested changes
needs rebase

2021-12-16 16:07 UTC, bartavelle commented
Build is failing because `curieconfctl` is broken :(

2021-12-18 07:00 UTC, flaper87 commented
> Build is failing because `curieconfctl` is broken :(

Do we have a bug for this? Do you know already what's broken?

2021-12-20 14:58 UTC, bartavelle commented
I tracked it down last time but just forgot, I think it was a dependency problem, lemme check it again.

2021-12-20 15:05 UTC, bartavelle commented
I filed this issue : https://github.com/curiefense/curiefense/issues/645

2022-01-03 12:31 UTC, flaper87 commented
@bartavelle maybe we can rebase this PR now? Tests should pass

2022-01-03 21:42 UTC, xavier-rbz commented on curiefense/curielogger/pkg/entities/curie_proxy_log.go
> +	Cfhost      string                 `json:"cfhost"`
After some debugging, I found out that the authority was already part of the received Json, we "just" needed to add it to the output structure. #657 does that.

2022-01-03 21:55 UTC, xavier-rbz commented
With this PR, the authority would be transmitted twice from envoy to curielogger: in `attributes.authority`, and in the `cfhost` fields introduced by this PR. I believe the approach I follow in #657 avoids duplication.
I wish I had read this PR before debugging that, though :D

2022-01-05 13:42 UTC, bartavelle commented
Then I guess we can close this PR?

2022-01-10 08:23 UTC, flaper87 commented
> Then I guess we can close this PR?

closing as it was superseded by #657

2022-01-10 08:23 UTC, closed without merging