(Draft) Validate Ban Actions
curiefense/curiefense pull request #647
Opened 2021-12-26 11:57 UTC by Freakachoo

# Changelog
- Validate Ban that rate limit can have only one Ban action
- Search Ban action before applying in rust code 
- Fix TESTING to TESTIMG in build script

2021-12-27 12:42 UTC, Aviv-Galmidi requested changes

2021-12-27 12:42 UTC, Aviv-Galmidi commented on curiefense/ui/src/doc-editors/RateLimitsEditor.vue
> +    checkOnlyOneBan() {
We can make this into a computed property instead of calculating it ourselves each time

2021-12-27 16:41 UTC, Freakachoo commented on curiefense/ui/src/doc-editors/RateLimitsEditor.vue
> +    checkOnlyOneBan() {
Done! Re-review please

2021-12-28 08:15 UTC, flaper87 approved these changes
Rust bits and limits look good to me :)

2021-12-28 12:50 UTC, Aviv-Galmidi commented on curiefense/ui/src/doc-editors/RateLimitsEditor.vue
> +    updateThresholdOption(option: OptionObject, index: number) {
We can remove this function now and call emitDocUpdate directly

2021-12-28 12:58 UTC, Aviv-Galmidi approved these changes

2021-12-28 13:43 UTC, merged