Enable banning in flow control
curiefense/curiefense pull request #676
Opened 2022-01-25 15:47 UTC by bartavelle

This patch enables banning in flow control, and refactors limit checks a
bit so that common code is shared.

The currently noop test for banning flow control has also been
activated.

Signed-off-by: Simon Marechal <bartavelle@gmail.com>

2022-01-25 16:30 UTC, bartavelle commented
The build is broken:

```
curiesync        | Traceback (most recent call last):
curiesync        |   File "/usr/local/bin/curieconfctl", line 3, in <module>
curiesync        |     from curieconf import cli
curiesync        |   File "/usr/local/lib/python3.7/dist-packages/curieconf/cli/__init__.py", line 17, in <module>
curiesync        |     from curieconf import utils
curiesync        |   File "/usr/local/lib/python3.7/dist-packages/curieconf/utils/__init__.py", line 7, in <module>
curiesync        |     from flask_restx import fields
curiesync        |   File "/usr/local/lib/python3.7/dist-packages/flask_restx/__init__.py", line 4, in <module>
curiesync        |     from . import fields, reqparse, apidoc, inputs, cors
curiesync        |   File "/usr/local/lib/python3.7/dist-packages/flask_restx/reqparse.py", line 19, in <module>
curiesync        |     from .model import Model
curiesync        |   File "/usr/local/lib/python3.7/dist-packages/flask_restx/model.py", line 21, in <module>
curiesync        |     from jsonschema import Draft4Validator
curiesync        |   File "/usr/local/lib/python3.7/dist-packages/jsonschema/__init__.py", line 21, in <module>
curiesync        |     from jsonschema._types import TypeChecker
curiesync        |   File "/usr/local/lib/python3.7/dist-packages/jsonschema/_types.py", line 6, in <module>
curiesync        |     from pyrsistent import pmap
curiesync        | ModuleNotFoundError: No module named 'pyrsistent'
```

2022-01-25 16:49 UTC, bartavelle commented
The package is indeed installed, I do not know why it is not found :(

2022-01-25 16:51 UTC, bartavelle commented
```
root@curiesync:/# ls /usr/lib/python3.7/site-packages/pyrsistent
__init__.py  __init__.pyi  __pycache__	_checked_types.py  _field_common.py  _helpers.py  _immutable.py  _pbag.py  _pclass.py  _pdeque.py  _plist.py  _pmap.py	_precord.py  _pset.py  _pvector.py  _toolz.py  _transformations.py  py.typed  typing.py  typing.pyi
```

2022-02-08 09:05 UTC, Aviv-Galmidi submitted a review, later dismissed

2022-02-14 05:02 UTC, flaper87 requested changes
needs rebase

2022-02-14 05:02 UTC, flaper87 commented on curiefense/curieproxy/rust/curiefense/src/flow.rs
> +                            logs.debug("is banned!");
Is this debug line descriptive enough? Should it contain other things like the `ban_key`?

2022-02-14 08:12 UTC, bartavelle commented on curiefense/curieproxy/rust/curiefense/src/flow.rs
> +                            logs.debug("is banned!");
It should be better now!

2022-02-17 11:12 UTC, Aviv-Galmidi approved these changes

2022-02-21 08:20 UTC, bartavelle commented
@flaper87 can you check if the change corresponds to what you wanted? :)

2022-02-21 11:27 UTC, flaper87 approved these changes
Although it needs rebase now :(

2022-02-21 13:26 UTC, closed without merging