Add docs contribution section
curiefense/curiefense pull request #82
Opened 2021-01-27 17:24 UTC by flaper87

2021-01-27 17:45 UTC, jdorfman requested changes
We need to figure out how to merge `master` into `main` without breaking the build. The current link goes to an empty branch instead of https://github.com/curiefense/curiefense-gitbook/tree/master

2021-01-27 18:03 UTC, flaper87 commented
> We need to figure out how to merge `master` into `main` without breaking the build. The current link goes to an empty branch instead of https://github.com/curiefense/curiefense-gitbook/tree/master

Agreed, I can look into that.

We can prob do that as a follow-up task, unrelated from this PR. thoughts?

The link I used goes to the default branch, I think. It's the base link to thw repo. 🤔

2021-01-29 02:35 UTC, jdorfman commented
> We can prob do that as a follow-up task, unrelated from this PR. thoughts?

Check Slack. Spiros and I started a convo regarding docs

2021-01-29 16:30 UTC, jdorfman approved these changes

2021-01-29 16:30 UTC, merged