fixed rate limit symlink
curiefense/curiefense pull request #971
Opened 2022-10-21 18:43 UTC by tzuryby

Signed-off-by: Zuri Bar Yochay <tzury@reblaze.com>

2022-10-21 18:46 UTC, Freakachoo submitted a review, later dismissed

2022-10-21 19:20 UTC, Aviv-Galmidi submitted a review, later dismissed

2022-10-22 09:44 UTC, Freakachoo approved these changes

2022-10-22 09:48 UTC, Aviv-Galmidi approved these changes

2022-10-22 10:28 UTC, Aviv-Galmidi submitted a review, later dismissed

2022-10-22 10:41 UTC, Freakachoo approved these changes

2022-10-22 11:39 UTC, Freakachoo submitted a review, later dismissed

2022-10-22 11:51 UTC, Aviv-Galmidi approved these changes

2022-10-22 15:21 UTC, bartavelle requested changes

2022-10-22 15:21 UTC, bartavelle commented on curiefense/images/uiserver/Dockerfile
> +git clone https://github.com/reblaze/ui.git
you should use RUN here

2022-10-22 15:21 UTC, bartavelle commented on curiefense/images/uiserver/Dockerfile
> +cd ui
you should use WORKDIR here

2022-10-22 15:28 UTC, yitzchake approved these changes

2022-10-22 15:29 UTC, bartavelle approved these changes

2022-10-22 15:29 UTC, merged